import Head from 'next/head';
import Image from 'next/image';
// import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css';
import { useEffect, useRef, useState } from 'react';

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [products, setProducts] = useState<any[]>([]);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    fetch('/api/get-item')
      .then((response) => response.json())
      .then((data) => {
        setProducts(data.items);
      });
  }, []);

  const handleClick = () => {
    if (inputRef.current == null || !inputRef.current.value) {
      alert('name을 넣어주세요.');
      return;
    }

    fetch(`/api/add-item?name=${inputRef.current.value}`)
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        alert(data.message);
      });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <input ref={inputRef} type="text" placeholder="Input Item" />
          <button onClick={handleClick}>Add Jacket</button>
        </div>

        <div>
          <h3>Products List</h3>
          {products &&
            products.map((items) => {
              return (
                <div key={items}>
                  {JSON.stringify(items)}
                  <br />
                  <br />
                </div>
              );
            })}
        </div>
      </main>
    </>
  );
}
